### ISSUE TITLE
Async/Await in Build Output?

### ISSUE THREAD

**Issue by torch2424** [GoogleChromeLabs/comlink#366] opened 2019-09-18 00:31 UTC
Hello again, @surma 😂 

So I was having some funny build errors (Not working with [closure compiler](https://github.com/ampproject/rollup-plugin-closure-compiler), and Webpack was sad). Then, I looked through the [unpkg](https://unpkg.com/browse/comlink@4.0.2/dist/esm/comlink.mjs) and found a bunch of non-ES5 friendly code 🤔 

Is this by design? Usually bundlers will ignore anything in the `node_modules`, and I noticed in later versions things were transpiled down?

P.S it's the end of the day for me, so I may just be done for the day 😂

**Comment by surma** [comment] 2019-09-18 09:51
(TIL `unpkg.com/browse`, thanks for that!)

Yeah, I am following @justinfagnani’s guidance here. I publish untranspiled modules to npm. The reason for this is that publishing ES5 to npm has stifled our ecosystem’s ability to move forward. The fact that some bundlers will not transpile `node_modules` is actually the problem here. I am not sure if Webpack can be configured to behave otherwise.

FWIW, in my own projects I use TypeScript for transpilation and at that point you can just import the original TypeScript source file with an import:

```ts
import {expose} from "comlink/src/comlink.js";
```

That all being said: Is this just about async/await? If so, I only use it in one place and it’s probably fairly easy to rewrite that into a Promise chain.

**Comment by justinfagnani** [comment] 2019-09-18 16:12
I'm glad you're using my advice, @surma :)

I admit though that async functions are a tricky part. In much older browsers without generators they require the hefty regenerator runtime. If there's only one use I'd consider rewriting by hand. In LitElement though, we've definitely said that async is so key that we'll require the runtime on IE11.

Here's to hoping that new Edge finally kills off IE11!

**Comment by torch2424** [comment] 2019-09-18 17:07
@surma 

> (TIL unpkg.com/browse, thanks for that!)

You are welcome! 😄 

> Yeah, I am following @justinfagnani’s guidance here. I publish untranspiled modules to npm. The reason for this is that publishing ES5 to npm has stifled our ecosystem’s ability to move forward. 

Totally, I wholeheartedly agree with this! 👍 I agree that it's an ecosystem problem, thus I've been following things like the Javascript syntax year thing that @mathiasbynens and @kristoferbaxter have been working on to help resolve this issue. 

Unfortunately, I do think it has become the "standard" in the community to transpile modules, thus going against that should at least have some documentation with some help on how to do integrate into existing workflows where transpiled modules are expected 😄 

Do you think we could rename the [Browsers support and bundle size](https://github.com/GoogleChromeLabs/comlink#browsers-support--bundle-size) section to something like, "Usage Notes" or something like that? (Please help me think of a better name 😂 ) That way we can express why the output is not transpiled, and offer some quick globs on how to transpile a select set of your `node_modules` directory. That way already transpiled modules don't need to be re-transpiled, but for forward thinking modules, we can offer an easy snippet to enable this 🤔 

> The fact that some bundlers will not transpile node_modules is actually the problem here. I am not sure if Webpack can be configured to behave otherwise.

Yep, @justinfagnani Webpack (rollup, or whatever bundler) should be able to be configured to compiled node modules. 😄 To be honest, I was just fighting my rollup plugin for a little bit, and the figured, huh, maybe it was an unintentional down stream thing. Thus, I opened this issue, and now will go back to trying to find the right glob to get comlink transpiled 😂 

> FWIW, in my own projects I use TypeScript for transpilation and at that point you can just import the original TypeScript source file with an import:

Perfect I'll just do this 😄 

> That all being said: Is this just about async/await? If so, I only use it in one place and it’s probably fairly easy to rewrite that into a Promise chain.

Ah, so I think the async/await is fine! Let's keep using it! But I think this issue can become: Add some usage notes on transpiling the module in the README or something like that.

And thank you for the awesome advice / help @justinfagnani ! 😄

**Comment by sidhuko** [comment] 2019-10-07 01:59
You can specify to use "comlink/src/comlink.js" but the actual filesystem is named "comlink/src/comlink.ts" which causes errors to bubble up during webpack compilation when requesting the TS files directly or without extension because "protocols.js" is actually "protocols.ts" and the default settings won't find it in most build tools. I'm also not going to introduce latency into a webpack project on every import to make this work and potentially make it unclear to developers whether the file extension is correct or not just to account for an untranspiled package which is broken IMHO. You have a variety of ways using package.json or yarn workspaces which could help you distribute this package for node/umd/clientside. What you have currently does not work unfortunately! I'm replacing with an alternative package because there is no minimal solution for fixing these problems.  

https://docs.npmjs.com/files/package.json#browser
https://yarnpkg.com/lang/en/docs/workspaces/

**Comment by surma** [comment] 2019-10-07 10:07
I will look into removing async/await from the code as it is only used in one function and probably easily avoided. But I won't guarantee it. That being said:

> You can specify to use "comlink/src/comlink.js" but the actual filesystem is named "comlink/src/comlink.ts" which causes errors to bubble up during webpack compilation when requesting the TS files directly or without extension because "protocols.js" is actually "protocols.ts" and the default settings won't find it in most build tools. 

This is a bug in Webpack. TypeScript has always worked this way in that it will automatically prefer a `.ts` file for a `.js` import. If Webpack does not behave this way, Webpack is breaking compatibility and convention here.

> You have a variety of ways using package.json or yarn workspaces which could help you distribute this package for node/umd/clientside. 

I am already making use of these fields. Neither `main` nor `module` imply transpilation to ES5, tho. Both CommonJS as well as ESM can contain async/await. As I stated above, the fact that some people expect ES5 to get published to npm has stifled our ecosystem's ability to adopt modern JavaScript. Build tools like Webpack and Babel need to provide options to transpile dependencies. For Babel, for example, it's just a matter of adjusting the `exclude` config option, I think.

> What you have currently does not work unfortunately! I'm replacing with an alternative package because there is no minimal solution for fixing these problems.

Please do.

**Comment by sidhuko** [comment] 2019-10-07 11:21
> I will look into removing async/await from the code as it is only used in one function and probably easily avoided. But I won't guarantee it. 

I wouldn't focus on this issue as async/await isn't the only problem as you have the spread syntax being included which breaks Edge and older Safari versions. I think we can both agree you shouldn't ruin code clarity and quality for older browsers!

> This is a bug in Webpack. TypeScript has always worked this way in that it will automatically prefer a .ts file for a .js import.

This is not a bug in Webpack. The TypeScript compiler has this feature which is supported in their additional Module Resolution [1] because as a superset it requires a compilation step before it can be used in the browser. This gives some flexibility if the developer wishes to adopts new ESModule node resolution which defines an accurate extension must always be given for the ECMAScript modules `import` keyword [2] but it does not mean that supporting resolving '.js' and '.ts' (or vice versa) is part of the ECMAScript module specification or part of the node module resolution which other build tools (Webpack, Babel) write their tooling and base their test cases on. I could enable babel to process all files as TypeScript just for this single file but it would be a significant performance penalty for a small library.

[1] https://www.typescriptlang.org/docs/handbook/module-resolution.html#additional-module-resolution-flags
[2] https://nodejs.org/api/esm.html#esm_mandatory_file_extensions.


> If Webpack does not behave this way, Webpack is breaking compatibility and convention here.

With ES6 modules webpack relies on using babel, as node support for ES modules is still not LTS, so it's babel which propogates the error through Webpack when we compile our ES and TypeScript code. Our configuration is standard for projects using a mix of ES and TS. We use a variety of modules without issue and it's only this package causing a problem. Both Webpack and Babel comply to the node resolution specification so I cannot raise any issue with them. You're expecting them to support a TypeScript feature which is strictly contravening ESModule and Node.js ESModule specifications. Basically, you can only use the "comlink/src/comlink.js" hack if you are using the TypeScript compiler and it won't work for Babel and subsequently Webpack without your users having an in-depth knowledge of configuring these tools for bespoke requirements. Requirements which are offer neglible benefits at best. 

> I am already making use of these fields. 

The suggestion here was the `browser` property, which you do not use, to define a transpiled and browser friendly version of your package: https://docs.npmjs.com/files/package.json#browser. 


> Neither main nor module imply transpilation to ES5, tho. Both CommonJS as well as ESM can contain async/await. As I stated above, the fact that some people expect ES5 to get published to npm has stifled our ecosystem's ability to adopt modern JavaScript. 

Yes because the module solution doesn't dictate the intended version of ECMAScript but if you used a much older version of Node.js without async/await then you would be able to use CommonJS without async await. ES modules were only supported once async await were already implemented in most engines so again I think you've confused an issue here. I think it's a strong statement to say it has stifled adoptability and it's quite assumptious to believe every user in the world can afford a brand new PC or mobile with the latest browsers. The same applies within corporations with slim profit margins or governments saving your tax dollars. We're no longer back in the days of IE7/8 though so we're a lot further ahead then we were! 

> Build tools like Webpack and Babel need to provide options to transpile dependencies. For Babel, for example, it's just a matter of adjusting the exclude config option, I think.

Yes, we do transpile dependencies in our project every day using Webpack/Babel/Yarn workspaces to avoid having a watch command for each package. The issue with your package is that you expect ES modules to abide to the "additional module resolution" which is only available enabled by default in the TypeScript compiler and not supported in any other compiler without a significant performance impact of processing all JS files as TypeScript as well. It seems a bit OTT for one file, right?

**Comment by sidhuko** [comment] 2019-10-07 12:38
As discussed, easy fix would be to compile an alternative file for the package.json `browser` property using es5, I've tested the PR and it's working for us. Alternatively, I'll start distributing on a separate npm package for now as need these changes quite urgently! Thanks for your understanding.

https://github.com/GoogleChromeLabs/comlink/pull/376/files

**Comment by surma** [comment] 2019-10-08 10:12
Thanks for your PR @sidhuko.

I understand where you are coming from. If you have to support older browsers, you are doing hard and frustrating work. That being said, I am not comfortable linking up the `module` field to ES5. The ES5 version is 6.4KiB compared to the old 3.5KiB. That's almost double the file size (and that ratio carries over to gzip, too)! I can't — with a good conscience — have all modern browsers pay a file size tax of that magnitude. So with that in mind, I will close your PR.

However, I do realize that some people might need ans ES5 version (although all browsers that have proxies can run the current output!). I could be convinced to add an ES5 build to my output, but I won't link it up in my `package.json`. Would that help with your problem? IIUC, you should be able to include the ES5 version with an explicit path. WDYT? 

> I wouldn't focus on this issue as async/await isn't the only problem as you have the spread syntax being included which breaks Edge and older Safari versions.

Thanks for mentioning this. I must have not realized that I am breaking Edge when publishing v4 (a full rewrite) of Comlink. I just released v4.0.4 which removes async/await (cc @torch2424!) and spread operator so the browser support table from the README is correct again.

Closing this issue as it was specifically about async/await.

**Closed by surma** 2019-10-08 10:12 UTC

**Comment by sidhuko** [comment] 2019-10-09 15:47
So basically this is a typescript project or es6+ project only? Perhaps
that case should be clearly defined in your documentation because their is
no way to transpile down like you suggest without a user forking this
repository to package their own distribution. Perhaps you should change the
name to ts-comlink?

I'll write that PR for docs too! I don't see how accepting this PR will
change anything about your existing support. I've done it in the most
unobtrusive manner where none of your existing users will notice at all.
The size increase is an unfortunate fact but 3kb on modern browsers is not
significant at all when you consider SPA performance impact in that area in
general. If you used the Babel compiler you might find core-js drastically
reduces that size anyway by restricting the unnecessary code generated. So
I find your comments more than bemusing and bewildering. When web workers
are supported across browsers I'm trying to target with your package the
only argument I see here is a lack of understand of ECMAScript for a
preference of Typescript so I guess your experience is pretty low in this
area. This is clear because your recommended advice isn't possible, using a
direct file import with many of the alternative typescript compilers which
exist, isn't possible because your use of typescript features which are
debated (i.e. const enum) on top of the additional node resolution module
options put within typescript to aid adoption into ECMAScript rather than
blocking it!

While I have my own opinions about the ecosystem in JavaScript in general
it is really telling what your experience is when you would enforce your
personal preferences in an open source package distributed under a company
organisation for someone's hard work which again doesn't affect any
existing integrations.

**Comment by surma** [comment] 2019-10-10 10:19
Just as a warning: The plethora of ad hominem in your posts here really don't help create a constructive discourse. It makes you come across like a jerk, to be honest.

> So basically this is a typescript project or es6+ project only? 

That is absolutely fair to say, Comlink is ES6+. And I think this is really the part where we seem to be having vastly different perceptions of the ecosystem. My current browser support matrix for Comlink is as follows:

- Edge 15 (Oct. 2016)
- Chrome 56 (Jan. 2017)
- Firefox 52 (Sep. 2016)
- Opera 43 (Feb. 2017)
- Safari 10.1 (Mar. 2017)
- Samsung Internet 6 (Sep 2017)

All these versions are between 2 and 2½ years old. Looking at [the usage table on caniuse.com](https://caniuse.com/usage-table), it's apparent that this browser support matrix covers the _vast_ majority of traffic. I think it's absolutely fair to consider ES6 the norm. 

There are a couple of browsers that can't use Comlink out-of-the-box. Opera Mini is not really good with dynamic content anyway. IE11 use Comlink but requires more work, as it needs a proxy polyfill.

> because their is no way to transpile down like you suggest without a user forking this repository to package their own distribution. Perhaps you should change the name to ts-comlink?

This project is written in TypeScript, but published as ES6 JavaScript. No need to give it a name implying it's TypeScript only. There _are_ multiple ways to transpile Comlink on a per-project basis, and I have pointed at some before. I know you can transpile Comlink because we have done it for [PROXX](https://github.com/GoogleChromeLabs/proxx) which runs on KaiOS. I don't know your projects setup, but transpiling Comlink is possible with a Webpack project as well. It's a matter of configuration.

> The size increase is an unfortunate fact but 3kb on modern browsers is not
significant at all when you consider SPA performance impact in that area in
general. 

It is literally my job to fight code bloat on the web. The attitude you have here is fairly common and I don't blame you, but this is exactly where I need to set a better example. 3kb _do_ matter.
