### ISSUE TITLE
Dealing with primitives alongside callbacks

### ISSUE THREAD

**Issue by dht** [GoogleChromeLabs/comlink#499] opened 2020-11-01 15:34 UTC
I saw primitives can be used synchronously on the iframe side:
```js
// iframe.html
function add(a, b) {
	return a + b;
}

// index.html
const response = await f.add(1, 3); // 12
```

However, when you want to mix primitives with callbacks you seem to have to use `await` for both:

Thus this implementation will work:
```js
// iframe.html
async function complex1(obj) {
	return await obj.aNumber + await obj.aCallback();
}

// index.html
response = await f.complex1(Comlink.proxy({
      a: 4,
      b: () => 8
})); // 12
```

but this will not:
```js
// iframe.html
async function complex2(obj) {
	return obj.aNumber + await obj.aCallback(); // <===== no AWAIT before obj.aNumber
}

// index.html
response = await f.complex2(Comlink.proxy({
      a: 4,
      b: () => 8
})); // error thrown => TypeError: Cannot convert object to primitive value at Object.complex2
```

It may be counter intuitive for people who use our SDK to put await before what seems to be a simple primitive argument.

Is there a way for Comlink to distinguish between callbacks and primitives so we can keep the interface for our iframe users simple? 
```js
// iframe.html
async function simple(obj) {
	console.log(obj.version); 			// <===== simple aka primitives do not require async
	const repsonse = await obj.callback();
	...
}
```

If the only solution is to fork or build some kind of polyfill to extend the capabilities, we are of course willing to do so but I would like to validate it is the only option before doing so.

Btw, we've also tried proxying just the callback without much success:
```js
// iframe.html
 async function mix(obj) {
    try {
      return obj.a + await obj.callback();
    } catch (e) {
      console.log('e ->', e);
    }
  }

// index.html
 response = await f.mix({
      a: 5,
      callback: Comlink.proxy(() => 10)
}); // error thrown => TypeError: Cannot convert object to primitive value at Object.complex3
```

**Comment by chris-kruining** [comment] 2020-11-19 13:03
I', currently digging into this, but as far as I can resolve this wouldn't be possible with your current code, because the `obj` isn't transferred to the worker atm.

As far as I know you have 2 possibilities here:
1. `Comlink.tranfer`: I believe this should allow you to transfer your object to the worker. Watch out, only do this if you do not need the object on the calling side anymore, transfer is moving the memory access to the worker and removing it from the original side
2. a custom transfer handler: I must admid I do not know how exactly yo go about this one creating the handler itself is a piece of cake, but I'n not sure if it can be added to the handlers array.

I hope this helps you.

**Comment by chris-kruining** [comment] 2020-11-19 13:10
https://github.com/GoogleChromeLabs/comlink/blob/520e4d64072bc07c3c60dd67dd95910a23602445/src/comlink.ts#L276 handlers are exported, so you can indeed add your own to the list

**Comment by surma** [comment] 2021-01-25 12:34
Yes, primitives are turned into promises, too. Comlink proxies the entire object, so when you access a prop, it needs to check what the _current_ value is (as it may have changed since the proxy was created). So this is working as intended.

If you want to copy some values and proxy some others, I suggest splitting them into separate parameters.

**Closed by surma** 2021-01-25 12:34 UTC

**Comment by yume-chan** [comment] 2023-04-30 17:30
> I suggest splitting them into separate parameters.

Is that possible with return values?

```js
Comlink.expose(() =>({
   a: 1, // need to be cloned
   b: new Uint8Array([1,2,3]), // need to be transferred
   c: () => 1, // need to be proxied
});
```
