### ISSUE TITLE
Posting huge Maps is slow

### ISSUE THREAD

**Issue by NicolasRannou** [GoogleChromeLabs/comlink#497] opened 2020-10-14 15:19 UTC
Hello,

I am not sure it is a comlink issue (need to perform more tests) but I noticed that it is extremely slow to post a message if I pass a *huge* map as an argument.

It takes about 5seconds (!) to perform the copy of a 2.5 million items map whereas a smaller map of about 50k items is instantaneous.

The main issue is that it appears that the post is blocking the main thread.

From the testing you did [there](https://surma.dev/things/is-postmessage-slow/), it is reasonable to expect a larger upload time but I was very surprised to get such a performance issue.

Would the workaround be to move to a different type structure (transferable object or SharedArrayBuffer for instance)? Or should we still expect well < 1s post time, even for very large structures?

Thanks for any comments/suggestions!
Cheers

**Comment by surma** [comment] 2021-01-25 12:31
I mentioned this to the V8 team, and structured cloning Maps is apparently not very optimized in V8 (but also not very common). The team is aware, but either way, this is not a bug with Comlink. Closing this for now.

**Closed by surma** 2021-01-25 12:31 UTC
